# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setGeometry(QtCore.QRect(0, 0, 641, 461))
        self.mainWidget.setObjectName("mainWidget")
        self.rightWidget = QtWidgets.QWidget(self.mainWidget)
        self.rightWidget.setGeometry(QtCore.QRect(150, 0, 491, 461))
        self.rightWidget.setObjectName("rightWidget")
        self.scrollArea = QtWidgets.QScrollArea(self.rightWidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 489, 331))
        self.scrollArea.setStyleSheet("#scrollWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollWidget.setGeometry(QtCore.QRect(0, 0, 468, 331))
        self.scrollWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollWidget.setObjectName("scrollWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollWidget)
        self.msgWidget = QtWidgets.QWidget(self.rightWidget)
        self.msgWidget.setGeometry(QtCore.QRect(0, 340, 491, 121))
        self.msgWidget.setObjectName("msgWidget")
        self.textEdit = QtWidgets.QTextEdit(self.msgWidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 489, 121))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setStyleSheet("padding: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushBtn = QtWidgets.QPushButton(self.msgWidget)
        self.pushBtn.setGeometry(QtCore.QRect(390, 80, 91, 28))
        self.pushBtn.setObjectName("pushBtn")
        self.leftWidget = QtWidgets.QWidget(self.mainWidget)
        self.leftWidget.setGeometry(QtCore.QRect(0, 0, 141, 461))
        self.leftWidget.setObjectName("leftWidget")
        self.groupList = QtWidgets.QListWidget(self.leftWidget)
        self.groupList.setGeometry(QtCore.QRect(0, 0, 141, 461))
        self.groupList.setObjectName("groupList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9.16364pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"></span></p></body></html>"))
        self.textEdit.setPlaceholderText("此处输入文字...")
        self.pushBtn.setText(_translate("MainWindow", "发送"))
